### ISSUE TITLE
Water speed doesn't seem to be working

### ISSUE THREAD

**Issue by MisionThi** [DaFuqs/AdditionalEntityAttributes#10]
When setting the attribute: `additionalentityattributes:water_speed` nothing seems to change.

**Comment by DaFuqs** [comment]
could you elaborate a bit more, please?
What command did you use? Any other mods installed? Are there errors in the log?

An example command would be:
`/attribute @s additionalentityattributes:water_speed modifier add 135e1f1e-755d-4cfe-82da-3648626eeba2 test 2.0 multiply_base`

**Comment by MisionThi** [comment]
I was using this command: `/attribute @s additionalentityattributes:water_speed base set 20`
