### ISSUE TITLE
Forge port?

### ISSUE THREAD

**Issue by iTheMooster** [DaFuqs/AdditionalEntityAttributes#12]
Would u actively try to learn a entire new code language for literally some random on the internet for a version of minecraft thats dying slowly as we speak?

**Comment by ChrysanthCow** [comment]
[EdwinMindcraft/AdditionalEntityAttributes](https://github.com/EdwinMindcraft/AdditionalEntityAttributes/)

Here's a fork of this mod used in the Forge port for Origins, it's a tad behind though, as is that mod.

**Comment by DaFuqs** [comment]
^ dis is de wey
