### ISSUE TITLE
Move away from JitPack

### ISSUE THREAD

**Issue by ChrysanthCow** [DaFuqs/AdditionalEntityAttributes#17]
I'm most likely going to just link what I said on Origins Fabric's issues page.

https://github.com/apace100/origins-fabric/issues/682

Point is, JitPack has proven to be quite unreliable as the main maven to depend on, and has actively made developing with Origins in mind a living nightmare for those who won't fork the repo(s) and make their own changes to them.

**Comment by DaFuqs** [comment]
I very much experienced that myself. That is why [AEA is also available on Modrinth](https://modrinth.com/mod/additionalentityattributes/versions). This allows you pull the jar via the modrinth maven: https://docs.modrinth.com/docs/tutorials/maven/

Works like a charm.

**Comment by ChrysanthCow** [comment]
I'd recommend making a readme to tell devs to use the modrinth maven then.

As it might not be super obvious to devs at first.

I'll probably PR an update for Apoli that uses this maven then.

Cheers

**Comment by DaFuqs** [comment]
done ✅
