### ISSUE TITLE
Permission to post Additional Entity Attributes Forge to Modrinth?

### ISSUE THREAD

**Issue by ChrysanthCow** [DaFuqs/AdditionalEntityAttributes#18]
Hi, I'm just writing here to let you know that I might publish AEA Forge to Modrinth once I rewrite and it becomes a NeoForge mod in 1.20.2.

I'm also notifying you because I want you to be listed as the Original Author on the modpage, and that we should probably discuss the split in terms of revenue between you, myself and EdwinMindcraft.

**Comment by DaFuqs** [comment]
Sure, feel free to post the NeoForge version on Modrinth!

I'm not too sure how much effort it was to port the mod to Forge, so feel free to choose a % that you find appropriate.

**Comment by DaFuqs** [comment]
Looks good to me. Ty for the port!
