### ISSUE TITLE
Suggestion: add attribute description lang keys

### ISSUE THREAD

**Issue by Partonetrain** [DaFuqs/AdditionalEntityAttributes#22]
Zenith Attributes adds an attributes screen, which can use description language keys.

this attribute is from a different mod but it's all the same format
![image](https://cdn.discordapp.com/attachments/973561602148270143/1183121732941389884/image.png?ex=65872efa&is=6574b9fa&hm=ebc52376303e962a91816d5f646ada6e791b3ebc076458ad4ab004e40d0eb801&)

**Comment by DaFuqs** [comment]
Sure!

**Comment by DaFuqs** [comment]
done
