### ISSUE TITLE
Incompatible with porting lib

### ISSUE THREAD

**Issue by AlphaMode** [DaFuqs/AdditionalEntityAttributes#29]
Switching to use ModifyExpressionValue should fix the issue
https://github.com/DaFuqs/AdditionalEntityAttributes/blob/1c6cb03cd3b2a2195f8d9274d885cb721d3362a9/src/main/java/de/dafuqs/additionalentityattributes/mixin/common/PlayerEntityMixin.java#L38

**Comment by DaFuqs** [comment]
Merged!
Will run some final tests and then release a updated jars.
