### ISSUE TITLE
Installing Polytone makes the game crash.

### ISSUE THREAD

**Issue by eydrien-dev** [DaFuqs/AdditionalEntityAttributes#32]
When I install [Polytone](https://modrinth.com/mod/polytone) (This is on Fabric 1.20.1) I get this crash error about additional entity attributes.

![javaw_bU8vGBRgvd](https://github.com/DaFuqs/AdditionalEntityAttributes/assets/9974516/0f044ef2-fb02-4698-a513-f9fbb7ec8d3b)

edit: forgot to mention, additional entity attributes is installed on the processedMods folder by default (additionalentityattributes-1.4.0) and I'm not sure which mod is installing it, but I leave the version here in case it helps.

edit 2: I realized that installing the mod on the normal mod folder, avoids auto install on processedMods, so I tried all the versions available for 1.20.1 and they all gave this error, except for 1.3.0, which basically stopped a lot of the mods I have from working.

**Comment by Noaaan** [comment]
Could you provide a full log from your launcher/instance? The Fabric Launcher popup isn't really clear in what is going wrong in your instance, since loading Spectrum and Polytone alone works fine.

**Comment by eydrien-dev** [comment]
Forgot to came back here, but the solution was fixed talking to the dev of Polytone.
