### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Felisinnn** [DaFuqs/AdditionalEntityAttributes#39]
Log: https://mclo.gs/jjstf3q
Sorry if this is not related to your mod

**Comment by DaFuqs** [comment]
Probably not, but I will happily help out.

> 03:04:56] [main/ERROR]: Mixin prepare for mod c2me-opts-allocs failed preparing MixinIdentifier in c2me-opts-allocs.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: c2me-opts-allocs.mixins.json:MixinIdentifier from mod c2me-opts-allocs target net.minecraft.class_2960 was loaded too early.

try removing / updating / downgrading c2me and see if it starts up
