### ISSUE TITLE
TPS Spiking via Recipes?

### ISSUE THREAD

**Issue by archynoid** [DaFuqs/AdditionalEntityAttributes#8]
I've been going around trying to get to the bottom of the TPS lag that is occuring on a server I am running. TPS spikes hard as more and more people join and it doesn't recover unless people leave. After going around a few different places I was able to find my way here. I have a few screenshots of what is doing most of the load, do you have any idea what this might be?

[1](https://i.imgur.com/FRbx4RU.png)
[2](https://i.imgur.com/FRbx4RU.png)
[3](https://i.imgur.com/MSy69rV.png)
[4](https://i.imgur.com/WWhXcF3.png)

**Comment by DaFuqs** [comment]
Source is Apoli, one of the mayor libraries Origins uses. You can report your findings here: https://github.com/apace100/apoli/issues

Though that might very well be treating a symptom instead of a cause. Try looking at what runs the `ClearInventory` command and if that is very frequent.

**Comment by DaFuqs** [comment]
@apace100 fyi

**Comment by archynoid** [comment]
It says additional entity attributes.

**Comment by archynoid** [comment]
This is also under the thread for Additional entity attributes in general, refer to screenshot 3 and 4

**Comment by archynoid** [comment]
Also if it isn't Additional Entity Attributes (which spark is saying it is) how would I go about figuring out what mod does it?
